services:

  portainer:
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    container_name: portainer_server
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appData/portainer:/data